name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Docker Image from Docker Hub
        run: docker pull lynas/publish-test:latest
      - name: Deploy to Render Web Service
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          render services update cu7d53tsvqrc7397u770 \
            --env docker \
            --docker-image lynas/publish-test:latest

